### ISSUE TITLE
How can I check where an email alert is used?

### ISSUE THREAD

**Issue by JeffKrakowski** [pgonzaleznetwork/sfdc-happy-soup#104]
How can I check where an email alert is used?

**Comment by pgonzaleznetwork** [comment]
@JeffKrakowski Thanks for the feedback! I believe this metadata type is not supported by the dependency API, but I may be able to build a custom query to find such alerts. 

On the other hand, when you are looking at an email alert in the salesforce UI, I think you can see which workflows are using this alert. Is this your use case?

**Comment by JeffKrakowski** [comment]
I could not find it, b/c it was reference By Process builder (same thing in
a flow)
Very hard to find things in Process builder, so anything you can set up
would be wonderful.

**Comment by pgonzaleznetwork** [comment]
Process Builders are indeed very tricky. I'll look into it!

**Comment by pgonzaleznetwork** [comment]
Hi @JeffKrakowski ,

Email Alerts are now available and you can see if they are being used by Process Builder! See below:

<img width="973" alt="Screenshot 2021-03-20 at 14 00 02" src="https://user-images.githubusercontent.com/8467087/111871935-94cbba80-8984-11eb-9f4b-6cd5d7db3ea7.png">

Enjoy and let me know if you have any questions!

**Comment by JeffKrakowski** [comment]
A big thank you for this, and helping u as admins shine 🌞

**Comment by JeffKrakowski** [comment]
Thank you for HappySoup

I am sometimes asked where an org-wide email is used
Is this possible via happy soup?
Looking forward to hearing from you
YK

**Comment by JeffKrakowski** [comment]
How can I find an email template based on the the email subject line?

>

**Comment by JeffKrakowski** [comment]
-- 

      Jeffrey Krakowski
 *Salesforce Consulting & Administration*
      www.sfchamp.com
      Linkedin.com/in/salesforcechamp
<https://www.linkedin.com/in/SalesforceChamp>

      US: (929) 445-8125
      Israel:054-292-7770
        Join me on Zoom <https://olami.zoom.us/my/smile>
