### ISSUE TITLE
Check flexipages for dependencies

### ISSUE THREAD

**Issue by mr-freire** [pgonzaleznetwork/sfdc-happy-soup#131]
We have plenty of components on our Lightning Pages that have record visibility filters, which the tool is not picking up.
![image](https://user-images.githubusercontent.com/55545152/118016692-14925780-b32c-11eb-85fd-a518adaaee24.png)

This is stored as visibility rules on the flexipage metadata files
![image](https://user-images.githubusercontent.com/55545152/118016841-41df0580-b32c-11eb-9512-6704d2543491.png)

And it's not being detected by the tool
![image](https://user-images.githubusercontent.com/55545152/118016928-60450100-b32c-11eb-8122-97212622702c.png)

**Comment by pgonzaleznetwork** [comment]
Thanks for reaching out @mr-freire !! It appears that this dependency is not supported by the MetadataComponentDependency API, but the metadata of the flexipage does reflect the field being used

```
                "componentName": "flexipage:richText",
                "visibilityRule": {
                  "booleanFilter": null,
                  "criteria": [
                    {
                      "leftValue": "{!Record.CustomerPriority__c}",
                      "operator": "EQUAL",
                      "rightValue": "High"
                    }
                  ]
                }
              },
              "fieldInstance": null
            }
          ],
          "mode": "Replace",
          "name": "sidebar",
          "prependable": null,
          "replaceable": null,
          "type": "Region"
        }
      ],
      "masterLabel": "Account Record Page",
      "parentFlexiPage": "sfa__Account_rec_L",
      "platformActionlist": null,
      "quickActionList": null,
      "sobjectType": "Account",
      "template": {
        "name": "flexipage:recordHomeTemplateDesktop",
        "properties": []
      },
```

So it should be possible to query all the flexipages that belong to the object that the field belongs to, and then query their metadata to see if the field is being used. This will be a performance hit though...How many flexipages do you have per object in average?

**Comment by mr-freire** [comment]
@pgonzaleznetwork it varies client to client - but it ranges from 1 - 5 at least on my experience

**Comment by pgonzaleznetwork** [comment]
Thanks! I'll look at implementing this in the future!

**Comment by pgonzaleznetwork** [comment]
@mr-freire I might support this in the long-term future as it might require some architectural changes. See the discussion on #129 if you are interested in the technical details.

**Comment by pgonzaleznetwork** [comment]
Hi @mr-freire ,

Sorry this took so long, but I'm happy to report that you can now see if a custom field (not standard fields) are used in FlexiPages. Thank you for the idea and enjoy!
