### ISSUE TITLE
Maybe not a bug

### ISSUE THREAD

**Issue by pacol85** [pgonzaleznetwork/sfdc-happy-soup#137]
This may not be a bug but a lot of metadata isn't displayed when using the tool (at least with standard fields). I had the task to find where the Opportunity.Amount field was used on an Org and the only Metadata it showed was Worflow Rules, Workflow Field Update and Validation Rules.
But it left out a lot of formula fields, Flows, Process Builders, list views, fieldsets and layouts. Can't say for code because there was no code related (at least no apex showed up for me when searching on VSCode).
But it would be a great plus to be able to display all those other metadata

**Comment by pgonzaleznetwork** [comment]
Hi @pacol85 ,

Thanks for getting in touch! HappySoup.io is based on the MetadataComponentDependency 

https://developer.salesforce.com/docs/atlas.en-us.api_tooling.meta/api_tooling/tooling_api_objects_metadatacomponentdependency.htm

This object does NOT support standard fields. So the "where is this used" functionality for standard fields is entirely custom built, which means that unfortunately not every metadata is caught.

I will look into how to potentially add more metadata types for standard fields.

Thanks again!
