### ISSUE TITLE
Email Message Workflow Rules

### ISSUE THREAD

**Issue by jamienrogers222** [pgonzaleznetwork/sfdc-happy-soup#138]
Happy Soup did not return results for Email Message workflow rules.

**Comment by pgonzaleznetwork** [comment]
Hi @jamienrogers222 ,

Can you please expand on the use case here. What metadata type where you doing impact analysis on and what was the expected result?

**Comment by jamienrogers222** [comment]
Hi @pgonzaleznetwork , I was performing an impact analysis on the standard Case Status field (Case.Status). Happy Soup returned workflow rules for the Case object where Case.Status is referenced, but not Email Message workflow rules where Case.Status is referenced.

**Comment by pgonzaleznetwork** [comment]
@jamienrogers222  how was the Case.Status referenced in the workflow? as part of the criteria using a parent field? A screenshot (if possible) would be great!

**Comment by pgonzaleznetwork** [comment]
@jamienrogers222 sorry I just re-read your post, it's in the criteria! I'll look into this.

**Comment by pgonzaleznetwork** [comment]
@jamienrogers222 This feature is now available on HappySoup 2.0 BETA https://happysoup2-beta.herokuapp.com/

Give it a try and let me know if it works!

**Comment by jamienrogers222** [comment]
@pgonzaleznetwork it works!!!

**Comment by pgonzaleznetwork** [comment]
@jamienrogers222 great, thanks for the feedback! Please provide feedback on the new version of the app as well
