### ISSUE TITLE
UI defect: Donate button on home page overlapped by text

### ISSUE THREAD

**Issue by vikyaiyer** [pgonzaleznetwork/sfdc-happy-soup#140]
<img width="1440" alt="Screenshot 2021-07-17 at 4 55 44 PM" src="https://user-images.githubusercontent.com/12629498/126035382-47214591-32a9-4618-afba-6507997655dc.png">

**Comment by pgonzaleznetwork** [comment]
Thank you @vikyaiyer ! This only happens in small screens i believe. I will fix this in the next version of HappySoup.

For now , if you want to donate, you can use this link https://www.paypal.com/donate/?business=XEWHTYGFC5QEE&item_name=Support+HappySoup.io&currency_code=EUR
