### ISSUE TITLE
Not allowed by CORS at origin

### ISSUE THREAD

**Issue by Ashrithasfdc** [pgonzaleznetwork/sfdc-happy-soup#148]
I am testing happysoup locally using docker and I am seeing a CORS error while selecting the Metadata Type from UI(Localhost:3000). I have checked all the CORS settings in Vue.config.js and app.json, everything seems fine. Not sure what is happening. Please see below for error details.

We are sorry, something went wrong. Please click here to log a Github issue so that we can review the error. Please include the following details: Not allowed by CORS

Error: Not allowed by CORS at origin (/app/backend/routes/api/router.js:19:16) at /app/node_modules/cors/lib/index.js:219:13 at optionsCallback (/app/node_modules/cors/lib/index.js:199:9) at corsMiddleware (/app/node_modules/cors/lib/index.js:204:7) at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5) at next (/app/node_modules/express/lib/router/route.js:137:13) at next (/app/node_modules/express/lib/router/route.js:131:14) at next (/app/node_modules/express/lib/router/route.js:131:14) at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3) at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)

**Comment by pgonzaleznetwork** [comment]
Hey,

Thanks for reaching out! Your url needs to match exactly what's on the docker-compose.yml file, under the CORS_DOMAIN variable. See an example here 

https://github.com/pgonzaleznetwork/sfdc-happy-soup/blob/master/docker-compose.yml

Do they match? If yes and it's still not working, make sure they are EXACTLY the same (**L**ocalhost is not the same as **l**ocalhost)

**Comment by Ashrithasfdc** [comment]
Hey, Thanks for responding! It is same as in docker-compose.yml file. I am using localhost:3000. Please see attached screenshot. 
![url](https://user-images.githubusercontent.com/60669332/127383061-56d996b4-32ae-4ec3-b747-dd5bbf0cc6bd.JPG)

**Comment by pgonzaleznetwork** [comment]
Can you share a screenshot of your composer file? You can exclude the oauth stuff

**Comment by Ashrithasfdc** [comment]
Here you go

![image](https://user-images.githubusercontent.com/60669332/127385176-8e4bb4a1-2493-445b-9f8e-c9ee130e8b5e.png)

**Comment by pgonzaleznetwork** [comment]
That is strange. I haven't tested the local build with docker since I released the new UI with vue. I'll test it out myself and see if I can reproduce the issue. 

In the meantime, if you are curious, you could try adding a `console.log(origin)` right here

https://github.com/pgonzaleznetwork/sfdc-happy-soup/blob/5e7752fdda448c38ce67bf9889726baac675c54d/backend/routes/api/router.js#L13

Then run the app again with docker. Reproduce the issue and see what shows up in the terminal. The origin should be http://localhost but maybe your PC/browser is sending http://localhost:3000 (port included).

If that's the case, you'll have to add :3000 to the composer file. Let me know!

**Comment by Ashrithasfdc** [comment]
I added the port to composer file and ran the app. I am now able to access the metadata. I no longer see CORS error. Thanks!

![image](https://user-images.githubusercontent.com/60669332/127389393-6e4b6ebb-1c35-4748-ac54-52ca8e077476.png)

**Comment by pgonzaleznetwork** [comment]
That's great! I'll update the template to include the port number for future reference. Thanks for the feedback and enjoy the soup! :)

**Comment by Ashrithasfdc** [comment]
Thanks for the quick response. I am closing the ticket
