### ISSUE TITLE
Impact Analysis for Picklist Values

### ISSUE THREAD

**Issue by jamienrogers222** [pgonzaleznetwork/sfdc-happy-soup#154]
It would be great if Happy Soup could perform an impact analysis on picklist values.

For example, my team had to change all "Working" picklist values to "Active". Thus, we had to comb through metadata to find which picklist fields had a value of "Working". This was extremely difficult and time consuming.

**Comment by pgonzaleznetwork** [comment]
@jamienrogers222 thanks for reaching out! So what type of metadata did you have to go through to see if the value "Working" was being used?

I can think of

- Validation Rules
- Workflow rules/field updates
- Process Builder, flows
etc

Did you use HappySoup at all? it would've given you a baseline metadata to start with. Or was the result set too large and the process of checking which value was used was still too much?

**Comment by jamienrogers222** [comment]
@pgonzaleznetwork , all of that and Apex, Path Settings, Record Types, Support Processes, Lead Processes, Reports, Formula Fields, Lookup Filter, etc.

**Comment by pgonzaleznetwork** [comment]
@jamienrogers222 I can see how that would've been very time consuming. This might need to be a completely feature on its own and will take time to develop, but it's a great idea and I'll definitely look into this!

**Comment by jamienrogers222** [comment]
Thank you!!

**Comment by pgonzaleznetwork** [comment]
@jamienrogers222 I think the best solution here is to download the whole metadata of the org in vscode and then do a simple text search for the picklist value. This is way faster, more efficient and accurate than anything I could put together. Thanks for the feedback!
