### ISSUE TITLE
Account.ShippingAddress & Account.BillingAddress not listed?

### ISSUE THREAD

**Issue by marioessig** [pgonzaleznetwork/sfdc-happy-soup#157]
I would like to be able to query against **Account.ShippingAddress** as well as **Account.BillingAddress** to see where they are being used.

![image](https://user-images.githubusercontent.com/33463458/129967715-034f35b3-0d5f-46f6-91a5-8c2c95cfb291.png)

**Comment by pgonzaleznetwork** [comment]
Thanks for reaching out! I'll add these fields and it'll be ready tomorrow. I'll let you know!

**Comment by marioessig** [comment]
Looking forward to it!

**Comment by pgonzaleznetwork** [comment]
@marioessig I've added all the address fields documented on this page https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/compound_fields_address.htm

Please note that the Address field is a compound field, so for example, if an Account has the BillingCity populated, the BillingAddress will reflect that city as well, but BillingAddress will not be returned as being used in apex/validation rules unless it's used directly. Let me know if that makes sense.

Also be aware that (as documented in the docs above) the field names are different for each object:

Account >> Billing[FieldName] OR Shipping[FieldName]
Lead >> [FieldName]
Contact >> Mailing[FieldName]

I've added support for these 3 standard objects.

Also, be aware that the Salesforce API does not provide any means to find standard field dependencies, so this feature of HappySoup is a best effort and not guaranteed to reveal all the places where the field is used.

Thanks!

**Comment by marioessig** [comment]
Yes, it makes sense with the Address field being a compound field. That is fine.

Unfortunately, these fields you added seem not to be working...
![image](https://user-images.githubusercontent.com/33463458/130087027-b5934d13-23b0-4581-a6f0-a71bce68bf9f.png)

**Comment by pgonzaleznetwork** [comment]
I must've done something wrong there. I'll investigate and get back to you!

Pablo

**Comment by pgonzaleznetwork** [comment]
@marioessig  Can you please try again?
