### ISSUE TITLE
Flow utilization in buttons not captures

### ISSUE THREAD

**Issue by katie-silorio-gc** [pgonzaleznetwork/sfdc-happy-soup#165]
I have flows that are utilized in buttons and subsequently page layouts. This utilization is not captured by the impact analysis feature.

![Screenshot 2021-09-07 155232](https://user-images.githubusercontent.com/86748793/132420607-835d99a6-1803-46be-af9d-94e14e9ef86d.jpg)
![Screenshot 2021-09-07 155447](https://user-images.githubusercontent.com/86748793/132420611-d6a40ebb-874c-4602-ae70-6fd238508fe6.jpg)

**Comment by pgonzaleznetwork** [comment]
Hi @katie-silorio-gc ,

Thanks for reaching out! This could be one of those dependencies that the Salesforce API does not support, but I may be able to pull it using other methods.

I will definitely look into this and get back to you.

**Comment by katie-silorio-gc** [comment]
Thank you!

**Comment by pgonzaleznetwork** [comment]
@katie-silorio-gc  I've deployed this now, please test it out. If you are happy, I'd appreciate a share on this post to let other users know that their requests will be considered!

**Comment by pgonzaleznetwork** [comment]
@katie-silorio-gc Also, this works specifically for quick actions of type flow, not buttons using the flow URL. What was your use case?

**Comment by pgonzaleznetwork** [comment]
I've enabled this for url buttons as well. It'll go live soon.
