### ISSUE TITLE
Possible to add Opportunity Contact Role field

### ISSUE THREAD

**Issue by rjpletsch** [pgonzaleznetwork/sfdc-happy-soup#169]
We're using opportunity contact roles a lot and I've been alerted that it seems the Role field is automatically changing from whatever the user sets to Decision Maker on all those added.  I don't see any flows, workflows, or process builders which affect it so I'm at a loss.

Note: I'm newer with the company and we just merged two orgs together so that's really why I have no idea what could be affecting this.

**Comment by pgonzaleznetwork** [comment]
Hi @rjpletsch ,

This object (and its fields) is not supported yet. However, I just joined a new company that has a free offering (actually free, not a trial) for visualising you org's metadata in a very cool format, and this allows for some impact analysis on standard fields. I just tried it in my org and the OpportunityContactRole.Role field is available

You can get the free tier here: app.salto.io/login?isFreeTier=true

If you want to give it a try I'm happy to jump on a call some time next week and help you set it up.

In the meantime I'll add this object/fields in my to-do list.

**Comment by pgonzaleznetwork** [comment]
@rjpletsch Did you get a chance to try the free tier? Let me know if I can help.
