### ISSUE TITLE
Add Product2.Description

### ISSUE THREAD

**Issue by bussemac** [pgonzaleznetwork/sfdc-happy-soup#170]
Was just looking to see where we were using this, doesn't seem like it's supported by Happy Soup yet. Can this be added?

**Comment by pgonzaleznetwork** [comment]
Hi @bussemac !!

Thanks for reaching out. I just added this and other product2 fields

![Screenshot 2021-12-10 at 15 08 45](https://user-images.githubusercontent.com/8467087/145596228-ba515167-52a2-4a6a-9f12-af438d07a15a.png)

Please remember that support for standard fields is limited so it's not guaranteed that you'll find all their dependencies. Let me know if I can do anything else!
