### ISSUE TITLE
Unable to find the field dependency of account.type

### ISSUE THREAD

**Issue by kulkarom** [pgonzaleznetwork/sfdc-happy-soup#171]
We are sorry, something went wrong. Please click here to log a Github issue so that we can review the error. Please include the following details: job stalled more than allowable limit

Error: Missing lock for job 00D3M0000008mntUAA.0053M000000VDVFQA4:usage-Account.Type-StandardField1639470643103 finished at Object.finishedErrors (/app/node_modules/bull/lib/scripts.js:185:16) at /app/node_modules/bull/lib/scripts.js:172:23 at runMicrotasks (<anonymous>) at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by pgonzaleznetwork** [comment]
Thank you @kulkarom for reporting this! That looks like a transient error, is this still happening? Did you try again?
