### ISSUE TITLE
Order.Status field not showing up

### ISSUE THREAD

**Issue by bendsito** [pgonzaleznetwork/sfdc-happy-soup#172]
Using the **Impact Analysis** tool, filtering by _Standard Fields_, when I type "Status" it only suggests the fields _Case.Status_ and _Lead. Status_, but _Order.Status_ is missing. The logged in user has access to this field. Am I doing something wrong?

**Comment by pgonzaleznetwork** [comment]
Hi @bendsito , 

This field is not yet available but I can add it for you quickly. Are there any order standard fields i should add?

**Comment by bendsito** [comment]
Hi @pgonzaleznetwork,

That would be wonderful and very much appreciated 😃

I can't think of any other fields right now. The tool works great and has been very helpful for me. Thanks a lot!

**Comment by mr-freire** [comment]
@pgonzaleznetwork Would it be possible to also add Campaign.Type? Do you want me to create a new issue?

**Comment by pgonzaleznetwork** [comment]
Hi @bendsito @mr-freire 

I just added this and a few other standard fields from the Order and Campaign type objects. I don't know how I didn't think about these initially! Thank you for the feedback and do let me know if it's not working!
