### ISSUE TITLE
Order Product Not Available

### ISSUE THREAD

**Issue by NF-Stew** [pgonzaleznetwork/sfdc-happy-soup#175]
Hello! 

I am looking to see where a standard field (End Date) on the Order Product (OrderItem) is used in my org. This does not appear to be an object that is currently supported and am kindly requesting that it be added.

Thank you!

**Comment by pgonzaleznetwork** [comment]
Hi @NF-Stew !

Thanks for reaching out. I've added 3 fields for this object

https://github.com/pgonzaleznetwork/sfdc-happy-soup/commit/3239b92094b9ade7728f6bdd3648e64a63c6690b

Let me know if I should add more.

Please note that impact analysis for standard fields is a "best effort" feature, and not guaranteed to return everything.
