### ISSUE TITLE
Unable to use https://happysoup.io/usage

### ISSUE THREAD

**Issue by Sommish** [pgonzaleznetwork/sfdc-happy-soup#185]
![image](https://user-images.githubusercontent.com/102514364/160360935-15d73920-5c61-42a9-af8b-5e7b1a37c3ab.png)

**Comment by pgonzaleznetwork** [comment]
Hi @Sommish ,

Are you a Salesforce Admin in your org?

**Comment by Sommish** [comment]
Yes

**Comment by pgonzaleznetwork** [comment]
You would only get that error if you don't have admin permissions. Are you 100% sure you are a full salesforce admin in your org, with the standard admin profile?
