### ISSUE TITLE
Task.Type Standard Field Unavailable

### ISSUE THREAD

**Issue by disco76** [pgonzaleznetwork/sfdc-happy-soup#191]
Please add support for standard **Task.Type** field, thanks!

**Comment by pgonzaleznetwork** [comment]
Hi there,

Please use Salto's free tier for this 

https://www.linkedin.com/posts/pablo-gonzalez-13a4b956_where-is-this-used-is-missing-on-standard-activity-6925060320965095424-dlhG?utm_source=linkedin_share&utm_medium=member_desktop_web
