### ISSUE TITLE
Support for check in ApexClasses and Report Types in Impact Analysis

### ISSUE THREAD

**Issue by phiff** [pgonzaleznetwork/sfdc-happy-soup#211]
Hi
When checking 'Where is this used' for a custom field it would be great if it could detect if the field is used in Report Types and Apex Classes.
Thanks

**Comment by pgonzaleznetwork** [comment]
Hi @phiff ,

This should work for apex classes already. Is it not working for you?

Report Types is not supported, for that, you can use Salto's free tier 

https://www.youtube.com/watch?v=-UteZbGxux0&ab_channel=Salto

But first, you'll have to configure your environment to include report types

https://www.youtube.com/watch?v=5NqKJJcfA0s&list=PLw8aI-Qt_Esbxm0b83isGQram3jZQW6vI&index=7&t=2s&ab_channel=Salto

**Comment by phiff** [comment]
Hi

Sorry - my bad 😊
It turned out, that the org where I tested with HappySoup.io the field was
not referenced in an Apex Class, but I was in the org where I id did the
comparison.



*Med venlig hilsen*
------------------------------
*Allan Pheiffer*

*Mobil: +45 25270312*


Den fre. 30. sep. 2022 kl. 17.59 skrev Pablo Gonzalez <
***@***.***>:

**Comment by pgonzaleznetwork** [comment]
No worries, still, try Salto's free tier!
