### ISSUE TITLE
All website navigation interactions redirect to "Workflow Migration Info" tab/page 

### ISSUE THREAD

**Issue by nwoNF** [pgonzaleznetwork/sfdc-happy-soup#222]
As of yesterday, any time I try to use any of HappySoup's features online, everything redirects to the new Workflow Migration Info tab. Therefore HappySoup online is currently unusable. 

Just giving @pgonzaleznetwork a heads up in case you're unaware.

**Comment by pgonzaleznetwork** [comment]
Thanks for reporting this issue. I'm ok vacation until Jan 15th so sadly
HappySoup will not be functional until then

**Comment by nwoNF** [comment]
Thanks, Pablo! Have a great vacation.

**Comment by nwoNF** [comment]
Update from Pablo posted on a different issue thread: https://www.linkedin.com/posts/pablis_salesforce-where-is-this-used-for-standard-activity-7018141099047141378-IEvl?utm_source=share&utm_medium=member_android

**Comment by pgonzaleznetwork** [comment]
This is now resolved. Thanks for your patience!
