### ISSUE TITLE
Opportunity.StageName not found

### ISSUE THREAD

**Issue by CloudTechRaz** [pgonzaleznetwork/sfdc-happy-soup#227]
I tried searching for **Opportunity.StageName** which I know is being used in a number of Flows and no results were returned. Are flows not supported for this standard field or am I doing something wrong?

**Comment by pgonzaleznetwork** [comment]
For standard fields it's best to use app.salto.io (another free app i work on) 

Check out this quick demo: https://youtu.be/JWinaJxFqyQ
