### ISSUE TITLE
Standard field for All Standard Objects - Not available

### ISSUE THREAD

**Issue by PrasannaTonal** [pgonzaleznetwork/sfdc-happy-soup#237]
hi Pablo,

I could not find standard fields for some of the standard objects. Is this part of the setting at your end or am I missing something?
Will you be including few of the other missing Standard fields for Standard objects for impact analysis?
The object I am trying to access is 'Asset' and field is 'SerialNumber'. 
Thanks in advance for your help!

Regards,
Prasanna

**Comment by pgonzaleznetwork** [comment]
Standard fields are now handled at app.salto.io, which is also 100% free! (I'm part of the project).

You can see a demo here https://www.youtube.com/watch?v=JWinaJxFqyQ&ab_channel=Salto
